# Generated by Django 3.2.12 on 2022-04-25 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Productos', '0002_producto_imagen_producto'),
        ('Pedidos', '0003_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='medio_pago',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_producto', models.IntegerField(default=0)),
                ('modo_venta', models.CharField(max_length=30, null=True)),
                ('cantidad_producto', models.IntegerField(default=0)),
                ('subtotal', models.IntegerField(default=0)),
                ('id_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pedidos.pedido')),
                ('id_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Productos.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='detalle_pedido',
            field=models.ManyToManyField(through='Pedidos.DetallePedido', to='Productos.Producto'),
        ),
    ]
