# Generated by Django 3.2.12 on 2022-04-25 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0004_auto_20220424_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='detalle_pedido',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_pedido',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
    ]
