# Generated by Django 3.2.12 on 2022-04-25 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0006_auto_20220424_2106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='id_pedido',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='detallepedido',
            old_name='id_producto',
            new_name='producto',
        ),
    ]
