# Generated by Django 3.2.12 on 2022-04-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('titular', models.CharField(max_length=40)),
                ('rut', models.CharField(max_length=12)),
                ('banco', models.CharField(max_length=30)),
                ('tipo_cuenta', models.CharField(max_length=20)),
                ('numero_cuenta', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
    ]
