# Generated by Django 3.2.12 on 2022-04-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_cuentabancaria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuentabancaria',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='cuentabancaria',
            table='CuentaBancaria',
        ),
    ]
