# Generated by Django 3.2.12 on 2022-04-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20220414_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuentabancaria',
            name='numero_cuenta',
            field=models.CharField(max_length=40),
        ),
    ]
