# Generated by Django 3.2.12 on 2022-05-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_producto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_producto',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
