# Generated by Django 3.2.12 on 2022-05-02 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtroGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_gasto', models.DateField(auto_now_add=True)),
                ('nombre_gasto', models.CharField(max_length=50)),
                ('monto_gasto', models.IntegerField(default=0)),
                ('descripcion_gasto', models.TextField(max_length=350)),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GastoProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_gasto', models.DateField(auto_now_add=True)),
                ('monto_frutas', models.IntegerField(default=0)),
                ('monto_verduras', models.IntegerField(default=0)),
                ('monto_bolsas', models.IntegerField(default=0)),
                ('total_gasto', models.IntegerField(default=0)),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
