# Generated by Django 3.2.12 on 2022-05-12 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GastoProductos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_gasto', models.DateField()),
                ('monto_frutas', models.IntegerField(default=0)),
                ('monto_verduras', models.IntegerField(default=0)),
                ('monto_bolsas', models.IntegerField(default=0)),
                ('total_gastoproductos', models.IntegerField(default=0)),
                ('otros_gastos', models.IntegerField(default=0)),
                ('total_otrosgastos', models.IntegerField(default=0)),
                ('total_dia', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OtroGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_otrogasto', models.DateField(auto_now_add=True)),
                ('nombre_otrogasto', models.CharField(max_length=50)),
                ('monto_otrogasto', models.IntegerField(default=0)),
                ('descripcion_otrogasto', models.TextField(max_length=350)),
                ('main_gasto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gastos.gastoproductos')),
            ],
        ),
    ]
