# Generated by Django 3.2.12 on 2022-05-03 19:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gastos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otrogasto',
            old_name='descripcion_gasto',
            new_name='descripcion_otrogasto',
        ),
        migrations.RenameField(
            model_name='otrogasto',
            old_name='monto_gasto',
            new_name='monto_otrogasto',
        ),
        migrations.RenameField(
            model_name='otrogasto',
            old_name='nombre_gasto',
            new_name='nombre_otrogasto',
        ),
        migrations.RemoveField(
            model_name='otrogasto',
            name='fecha_gasto',
        ),
        migrations.AddField(
            model_name='otrogasto',
            name='fecha_otrogasto',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
