# Generated by Django 3.2.12 on 2022-05-03 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gastos', '0002_auto_20220503_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='otrogasto',
            name='main_gasto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Gastos.gastoproductos'),
        ),
        migrations.AlterField(
            model_name='otrogasto',
            name='fecha_otrogasto',
            field=models.DateField(auto_now_add=True),
        ),
    ]
