# Generated by Django 3.2.12 on 2022-05-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gastos', '0003_auto_20220503_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastoproductos',
            old_name='total_gasto',
            new_name='total_gastoproductos',
        ),
        migrations.AddField(
            model_name='gastoproductos',
            name='otros_gastos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gastoproductos',
            name='total_dia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gastoproductos',
            name='total_otrosgastos',
            field=models.IntegerField(default=0),
        ),
    ]
