# Generated by Django 3.2.12 on 2022-05-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gastos', '0004_auto_20220503_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoproductos',
            name='fecha_gasto',
            field=models.DateField(),
        ),
    ]
